# -*- coding: utf-8 -*-
"""19110046_ME 639 Assignment 2 Q12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16hd_okbVT4t82J3BL4iHOWHSL812Z01m
"""

import numpy as np
import math

#Variables Initialisation
l1 = float(input("Length 1 = "))
l2 = float(input("Length 2 = "))
l3 = float(input("Length 3 = "))
q1 = float(input("Angle of first revolute joint = "))
q2 = float(input("Angle of second revolute joint = "))

#Jacobian
J = np.array([[-l2*math.sin(q1)+l3*math.sin(q2)*math.cos(q1), -2*l2*math.cos(q1)*math.sin(q1), 0], [l2*math.cos(q1)+l3*math.cos(q2)*math.cos(q1), l2*math.cos(2*q1), 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 1, 0]])
print(J)

